### ISSUE TITLE
missing part of the path

### ISSUE THREAD

**Issue by dynamic-pindar** [yashag2255/iframePCF#2]
I keep getting the following error message when following the instructions to push the component to my environment. Is there something I'm missing?

Error: Could not find a part of the path 'C:\....\iframePCF\src\out\controls'.

**Comment by kimomar1102** [comment]
Im also having the same problem

**Comment by kimomar1102** [comment]
I found out how to solve this. Dont forget to use the "npm run build" in the setup of the PCF component.

**Comment by yashag2255** [comment]
Hey Guys! Hope you resolved with the npm run build (the reason is some files are ignored by the gitignore file and these files are automatically created when you build the solution and for more info on this you can refer to the .gitignore file). However, I have now attached the PCF solution directly in this repository so all you have to do is import the solution and use the component in the app. Hope this helps!

**Comment by dynamic-pindar** [comment]
thanks for the responses and the quick update!
